<<<<<<< HEAD
import './globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
=======
import { FC, PropsWithChildren } from "react";
>>>>>>> 17d54c6387f242459aeac62c8e56fcc9c56848ea

import "./ui/globals.css"



const RootLayout: FC<PropsWithChildren<{}>> = ({ children }) => {
    return (
        <html lang="es">
            <body>
                {children}
            </body>
        </html>
    );
};

export default RootLayout;